security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'bcrypt'
    providers:
        users_in_memory:             
            memory:
                users:
                    user:
                        password: "$2a$12$H3zOmLHilBdvnTHEHqnoVOLb4uRJ9u//sBTOK9qLF/AuEYjE/1bX6"
                        identifier: user
                        roles: ["ROLE_USER"]
                    admin:
                        password: "$2a$12$AeU2tSRFIXFwQqZ5eWffI.4eoX9FoFynJQYMdO8LkszuLWjyjxbT2"
                        identifier: admin
                        roles: ["ROLE_ADMIN","ROLE_USER"]
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            lazy: true
            http_basic: ~
            provider: users_in_memory

    access_control:
        - { path: ^/api/v1/products, roles: ROLE_ADMIN, methods: ["POST","PUT"] }
        - { path: ^/api/v1/products, roles: ROLE_USER, methods: ["GET"] }

when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4 # Lowest possible value for bcrypt
                time_cost: 3 # Lowest possible value for argon
                memory_cost: 10 # Lowest possible value for argon
