version: '3.8'

services:
  db:
    container_name: db
    image: postgres:12
    restart: always
    env_file:
      - .env
    ports:
        - 15432:5432

  php-fpm:
    container_name: php-fpm
    build:
      context: ./docker/php-fpm
    depends_on:
      - db
    links:
      - db:db
    env_file:
      - .env
    volumes:
      - ./:/var/www

  nginx:
    container_name: nginx
    build:
      context: ./docker/nginx
    volumes:
      - ./:/var/www
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/sites/:/etc/nginx/sites-available
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d
      - ./docker/logs:/var/log
    depends_on:
      - php-fpm
    ports:
      - "8000:80"
